/* ============================================================================
   VivaTech 2026 — programme officiel
   ----------------------------------------------------------------------------
   Réorganisation visuelle du programme officiel de VivaTech 2026
   (Paris Expo Porte de Versailles, 17–20 juin 2026).

   Source : programme officiel VivaTech — https://vivatech.com/sessions
   Les 124 sessions du MERCREDI 17 JUIN sont les données réelles publiées par
   VivaTech (titres, horaires, scènes, intervenants, tracks).
   Les 18, 19 et 20 juin seront ajoutés au fur et à mesure de leur publication.

   Structure data-driven : pour mettre à jour, éditez le tableau SESSIONS.
   ========================================================================== */

const DAYS = [
  { id: "2026-06-17", label: "Mer. 17", full: "Mercredi 17 juin", hours: "09:00 – 18:00", note: "Programme officiel" },
  { id: "2026-06-18", label: "Jeu. 18", full: "Jeudi 18 juin",    hours: "08:30 – 19:00", note: "À venir" },
  { id: "2026-06-19", label: "Ven. 19", full: "Vendredi 19 juin", hours: "08:30 – 18:00", note: "À venir" },
  { id: "2026-06-20", label: "Sam. 20", full: "Samedi 20 juin",   hours: "08:30 – 18:00", note: "Grand public" },
];

// Scènes utilisées le 17 juin (ordre d'affichage des colonnes)
const STAGES = [
  "Stage One", "VivaTech Theater", "Black Stage", "Purple Stage", "Red Stage",
  "Founders Arena", "Business Redefined Arena", "Future of Industries Arena",
  "Sovereignty Arena", "Executive Arena", "Investor Lounge", "Pitch Studio",
  "Discovery Stage", "Workshop B", "Business Plaza",
];

// Thèmes = tracks officiels VivaTech (code couleur)
const THEMES = {
  ai:           { label: "Intelligence artificielle", color: "#7c3aed" },
  scale:        { label: "Risk, Build & Scale",       color: "#0066cc" },
  health:       { label: "Santé & Longévité",         color: "#0d9488" },
  productivity: { label: "Productivité réinventée",   color: "#ea580c" },
  energy:       { label: "Énergie, GreenTech & Mobilité", color: "#16a34a" },
  sovereignty:  { label: "Souveraineté & Éthique",    color: "#4f46e5" },
  cyber:        { label: "Cybersécurité & Défense",   color: "#dc2626" },
  creative:     { label: "Industries créatives",      color: "#db2777" },
  deeptech:     { label: "Tech Beyond the Obvious",   color: "#0891b2" },
  other:        { label: "Autres sessions",           color: "#64748b" },
};

// Programme réel du 17 juin 2026 (124 sessions). theme = clé de THEMES.
const SESSIONS = [
  { day:"2026-06-17", start:"09:15", end:"09:45", stage:"VivaTech Theater", theme:"other", title:"Opening Ceremony", speakers:["Maurice Lévy (Publicis Groupe)","Bernard Arnault (LVMH)"] },
  { day:"2026-06-17", start:"09:30", end:"10:30", stage:"Pitch Studio", theme:"creative", title:"Final of the we are_ Startup Challenge", speakers:["Peter Hopwood"] },
  { day:"2026-06-17", start:"09:45", end:"10:50", stage:"Purple Stage", theme:"scale", title:"Beyond the Big Names: Where the Next AI Leaders Are Emerging Globally", speakers:["Ahmad Ali Alwan (Hub71)","Stephan Kuester (Startup Genome)","Jarek Kutylowski (DeepL)"] },
  { day:"2026-06-17", start:"09:45", end:"10:30", stage:"Red Stage", theme:"health", title:"Machines That Care: Can Social Robots Redefine Human-Centered Healthcare?", speakers:["Joanne Hackett (IQVIA)","Dor Skuler (Intuition Robotics – ElliQ)","Greg Williams (Exponential View)"] },
  { day:"2026-06-17", start:"09:45", end:"10:00", stage:"VivaTech Theater", theme:"sovereignty", title:"Welcome Speech — Country of the Year", speakers:["Karsten Wildberger (Germany)","Roland Lescure (France)"] },
  { day:"2026-06-17", start:"09:55", end:"10:25", stage:"Black Stage", theme:"productivity", title:"From Pilot to Production: Scaling AI Agents Across the Pharma Value Chain", speakers:["Joel Belafa (Biolevate)","Artemiy Gvozdev (Sanofi)","David Ruau (Nvidia)"] },
  { day:"2026-06-17", start:"10:00", end:"10:45", stage:"Founders Arena", theme:"scale", title:"From Pre-Seed to Series A: Inside the Investors Mind", speakers:["Valerie Bures (XAnge)","Sofia Dahoune (daphni)","Jeremy Navon (Pitch My Startup)"] },
  { day:"2026-06-17", start:"10:00", end:"11:00", stage:"Executive Arena", theme:"scale", title:"Corporate Innovation Track / Breakfast by VivaTech & Bpifrance le Hub", speakers:["Paul-François Fournier (Bpifrance)","Peter Koerte (Siemens)","Yannick Marin (Airbus)"] },
  { day:"2026-06-17", start:"10:00", end:"10:25", stage:"VivaTech Theater", theme:"sovereignty", title:"United by Innovation: German Tech for a Stronger Europe", speakers:["Sebastian Borek (HTGF & DTCF)","Deepa Gautam-Nigge (SAP)","Meike Neitz (embassidy)"] },
  { day:"2026-06-17", start:"10:00", end:"10:10", stage:"Discovery Stage", theme:"ai", title:"Industry, Robotics & Advanced Manufacturing — Live Demo with TETMET", speakers:["Tom Vroemen (TETMET)"] },
  { day:"2026-06-17", start:"10:00", end:"11:00", stage:"Business Plaza", theme:"ai", title:"The AI Battle workshop", speakers:["Latifa Lhami (Learning Pro)","Callista Spiteri","Christ'All Tobossi"] },
  { day:"2026-06-17", start:"10:15", end:"10:25", stage:"Discovery Stage", theme:"health", title:"Industry, Robotics & Advanced Manufacturing — Live Demo with Gogoa", speakers:["Carlos Fernandez Isoird (Gogoa)"] },
  { day:"2026-06-17", start:"10:30", end:"11:15", stage:"Black Stage", theme:"productivity", title:"Brands in the Age of Algorithms: How to Build Affinity in an Artificial Space?", speakers:["Eduardo Barbaro (Tiffany & Co)","Clarisse Magnin (McKinsey)","Derya Matras (Meta)"] },
  { day:"2026-06-17", start:"10:30", end:"10:55", stage:"Future of Industries Arena", theme:"health", title:"From idea to impact: voices shaping health entrepreneurship", speakers:["Alexia Adda (Klava)","Christine Hanon (MyLifeCare)"] },
  { day:"2026-06-17", start:"10:30", end:"10:40", stage:"Discovery Stage", theme:"productivity", title:"Industry, Robotics & Advanced Manufacturing — Live Demo with Emiotech", speakers:["Philippe Houpert (Emiotech)"] },
  { day:"2026-06-17", start:"10:40", end:"11:05", stage:"Red Stage", theme:"deeptech", title:"Bioprinting: When Science Outpaces the System", speakers:["Tamer Mohamed (Aspect Biosystems)","Chris O'Brien (The French Tech Journal)"] },
  { day:"2026-06-17", start:"10:40", end:"11:40", stage:"Pitch Studio", theme:"productivity", title:"Final of the ManpowerGroup Startup Challenge", speakers:["Peter Hopwood"] },
  { day:"2026-06-17", start:"10:45", end:"11:30", stage:"Stage One", theme:"scale", title:"Digital Money, Real Power: The New Architecture of Finance", speakers:["Jeremy Allaire (Circle)","Rob Goldstein (BlackRock)","Arjun Kharpal (CNBC)"] },
  { day:"2026-06-17", start:"10:45", end:"11:30", stage:"Founders Arena", theme:"scale", title:"Master Your Fundraising Roadshow", speakers:["Maxime Guillaud (INSKIP)","Stéphanie Hospital (OneRagtime)","Zoe Qin (Dawn Capital)"] },
  { day:"2026-06-17", start:"10:45", end:"10:55", stage:"Discovery Stage", theme:"ai", title:"Industry, Robotics & Advanced Manufacturing — Live Demo with Botifull.ai", speakers:["Maxime Le Berre (Botifull.ai)"] },
  { day:"2026-06-17", start:"10:55", end:"11:10", stage:"Purple Stage", theme:"scale", title:"AI's Boom: Where Are Investments Going and Why?", speakers:["Nalin Patel (PitchBook)"] },
  { day:"2026-06-17", start:"11:00", end:"11:30", stage:"Business Redefined Arena", theme:"ai", title:"Beyond Copilots: Why the Future of AI Is the Full SDLC", speakers:["Bruno Aziza (IBM Software)","Amélie Hocquette (IBM)"] },
  { day:"2026-06-17", start:"11:00", end:"11:25", stage:"Future of Industries Arena", theme:"energy", title:"Beyond Decarbonization: Industrial Energy with FLEX'eBRID", speakers:["Pierre Cheyron (ENGIE)"] },
  { day:"2026-06-17", start:"11:00", end:"11:25", stage:"Sovereignty Arena", theme:"scale", title:"The European Advantage for Scaleups", speakers:["Serena Borbotti-Frison (Allied For Startups)","Nico de Luis (Shakers)","Marcel Queralt (Factorial)"] },
  { day:"2026-06-17", start:"11:00", end:"11:30", stage:"Executive Arena", theme:"other", title:"European Women in STEM Awards: Revealing Europe's Missing Talent", speakers:["Angélique Gérard (Women in STEM Europe)"] },
  { day:"2026-06-17", start:"11:00", end:"11:10", stage:"Discovery Stage", theme:"ai", title:"Live Demo with PAL ROBOTICS x LAAS (humanoïde Kangaroo)", speakers:["Maximilien Naveau (PAL Robotics)","Albert Tissot (PAL Robotics)"] },
  { day:"2026-06-17", start:"11:10", end:"11:40", stage:"Red Stage", theme:"health", title:"Beyond Borders: Can Remote Surgery Democratize Care?", speakers:["Louise Agersnap (WHO)","Ana Rold (Diplomatic Courier)","Jitendra Sharma (Kalam Institute)"] },
  { day:"2026-06-17", start:"11:15", end:"12:00", stage:"Purple Stage", theme:"scale", title:"Surfing the Wave: What is the Best Strategy to Invest in AI?", speakers:["Hala Fadel (Eurazeo)","Maya Noël (France Digitale)","Suzanne Ashman (Sovereign AI Ventures)"] },
  { day:"2026-06-17", start:"11:15", end:"11:25", stage:"Discovery Stage", theme:"ai", title:"Industry, Robotics & Advanced Manufacturing — Live Demo with Agibot", speakers:["Agibot"] },
  { day:"2026-06-17", start:"11:20", end:"11:35", stage:"Black Stage", theme:"productivity", title:"AI Changed the Productivity Equation. Are Leaders Ready?", speakers:["Margaux Gregoir (Serena)","Xavier Jaravel (London School of Economics)"] },
  { day:"2026-06-17", start:"11:30", end:"12:15", stage:"Founders Arena", theme:"scale", title:"The AI Fundability Stack: $50M Series A vs Stuck Seed Round", speakers:["Boris Golden (Partech)","Agnès Seuret (AWS)","Léa Verdillon (Aglaé Ventures)"] },
  { day:"2026-06-17", start:"11:30", end:"12:00", stage:"Business Redefined Arena", theme:"ai", title:"Building a Creative Workforce in the AI Era", speakers:["Caroline Levander (Rice University)","Soumia Malinbaum (Groupe JEMS)"] },
  { day:"2026-06-17", start:"11:30", end:"11:55", stage:"Future of Industries Arena", theme:"scale", title:"Context is Everything: The Future of Banking in an Agentic World", speakers:["Christopher Sanders (Quantexa)"] },
  { day:"2026-06-17", start:"11:30", end:"11:55", stage:"Sovereignty Arena", theme:"sovereignty", title:"Sovereignty Is the New Business Continuity", speakers:["Christel Heydemann (Orange)","Stéphane Pallez (FDJ United)","Laurent Benarousse (Roland Berger)"] },
  { day:"2026-06-17", start:"11:30", end:"12:00", stage:"Executive Arena", theme:"scale", title:"GTM Alpha: Building a Competitive Edge with Clay", speakers:["Archie Moore (Clay)"] },
  { day:"2026-06-17", start:"11:30", end:"11:40", stage:"Discovery Stage", theme:"ai", title:"Industry, Robotics & Advanced Manufacturing — Live Demo with KORBEN", speakers:["Quentin Bianchi (KORBEN)"] },
  { day:"2026-06-17", start:"11:40", end:"12:20", stage:"Black Stage", theme:"productivity", title:"The Autonomous Future: Can Industry 5.0 Compete When Machines Run the Show?", speakers:["Olivia Amozig-Bellot (La Poste)","Kathy Quashie (Inetum)","Julie Teigland (EY)"] },
  { day:"2026-06-17", start:"11:45", end:"12:10", stage:"Red Stage", theme:"health", title:"Longevity Unlocked: The Science Extending Human Healthspan", speakers:["Joan Mannick (Altos Labs)","Ana Rold (Diplomatic Courier)"] },
  { day:"2026-06-17", start:"11:45", end:"11:55", stage:"Discovery Stage", theme:"ai", title:"Industry, Robotics & Advanced Manufacturing — Live Demo with Zeroth", speakers:["Rong Hua (Zeroth)"] },
  { day:"2026-06-17", start:"12:00", end:"12:30", stage:"Business Redefined Arena", theme:"cyber", title:"Fluidity vs. Security: Can digital identity bridge the gap in critical infrastructure?", speakers:["Christophe Chollet (IN Groupe)","Julien Drouet (IN Groupe)"] },
  { day:"2026-06-17", start:"12:00", end:"12:25", stage:"Future of Industries Arena", theme:"energy", title:"From Compute to Steel: Decarbonizing AI Growth", speakers:["Stefanie Beekhuizen (Stegra)","Johan Mandaric Reunanen (Stegra)"] },
  { day:"2026-06-17", start:"12:00", end:"12:25", stage:"Sovereignty Arena", theme:"sovereignty", title:"Sovereign Solutions from the Industrial Ecosystem of Auvergne-Rhône-Alpes", speakers:["Délégation Auvergne-Rhône-Alpes"] },
  { day:"2026-06-17", start:"12:00", end:"12:30", stage:"Executive Arena", theme:"creative", title:"Art, Unlocked by ArtMajeur, an AI company", speakers:["Laurence Bonicalzi Bridier (ArtMajeur)","Stéphane Lévy (ArtMajeur)"] },
  { day:"2026-06-17", start:"12:00", end:"12:40", stage:"VivaTech Theater", theme:"energy", title:"Powering Europe's Green Industrial Renaissance in the Age of AI", speakers:["François Provost (Renault Group)","Lei Zhang (Envision)","Slawomir Krupa (Société Générale)"] },
  { day:"2026-06-17", start:"12:00", end:"12:10", stage:"Discovery Stage", theme:"ai", title:"Industry, Robotics & Advanced Manufacturing — Live Demo with Unitree", speakers:["Unitree"] },
  { day:"2026-06-17", start:"12:05", end:"12:20", stage:"Purple Stage", theme:"scale", title:"Building a Star Trek Vision", speakers:["Albert Wenger (Union Square Ventures)"] },
  { day:"2026-06-17", start:"12:15", end:"12:40", stage:"Stage One", theme:"ai", title:"Beyond the Chatbot: The Rise of AI Companions", speakers:["Norihiko Ishihara (Datasection)","Scott Trowbridge (Datasection)"] },
  { day:"2026-06-17", start:"12:15", end:"13:00", stage:"Red Stage", theme:"health", title:"Who's Missing? Building Equitable Healthcare Systems in the Age of AI", speakers:["Moojan Asghari (Women in AI)","Joanne Hackett (IQVIA)","Alex Ng (Tencent Healthcare)"] },
  { day:"2026-06-17", start:"12:15", end:"12:25", stage:"Discovery Stage", theme:"ai", title:"Industry, Robotics & Advanced Manufacturing — Live Demo with Genesis AI", speakers:["Théophile Gervet (Genesis AI)"] },
  { day:"2026-06-17", start:"12:25", end:"13:00", stage:"Black Stage", theme:"productivity", title:"The Industrial-Scale Reshuffle: How Are Machine Collabs Transforming Work?", speakers:["Riccardo Barberis (ManpowerGroup)","Erkki Keldo (Government of Estonia)","Samantha Gloede (KPMG)"] },
  { day:"2026-06-17", start:"12:25", end:"12:40", stage:"Purple Stage", theme:"ai", title:"Building for the Agentic Internet", speakers:["Linda Tong (Webflow)"] },
  { day:"2026-06-17", start:"12:30", end:"14:30", stage:"Workshop B", theme:"scale", title:"Seoul Forward: Make Seoul Your Next Move", speakers:["Ji Hyung Lee (Invest Seoul)","Pierre Joo (Korelya Capital)","Jean-Luc Maria (Exotrail)"] },
  { day:"2026-06-17", start:"12:40", end:"12:55", stage:"Stage One", theme:"ai", title:"The Symbiotic Enterprise: How Cognitive & Physical AI Are Reinventing Execution", speakers:["Stéphane Bout (McKinsey & Company)"] },
  { day:"2026-06-17", start:"12:40", end:"13:00", stage:"Purple Stage", theme:"scale", title:"From a Berlin Basement to a European Champion: the Zalando Story", speakers:["Robert Gentz (Zalando)","Mariam Zaidi (TRT World)"] },
  { day:"2026-06-17", start:"12:55", end:"13:20", stage:"VivaTech Theater", theme:"ai", title:"The Starting Line: Why AI's Biggest Breakthroughs Are Still Ahead", speakers:["Peter DeSantis (Amazon)","Nicholas Thompson (The Atlantic)"] },
  { day:"2026-06-17", start:"13:00", end:"13:30", stage:"Stage One", theme:"sovereignty", title:"Can Europe Build Global Champions?", speakers:["Ekaterina Zaharieva (European Commission)","Jean-Charles Samuelian (Alan)","Greg Williams (Exponential View)"] },
  { day:"2026-06-17", start:"13:20", end:"14:10", stage:"VivaTech Theater", theme:"ai", title:"Siemens Keynote: Industrial Tech for the AI Era", speakers:["Roland Busch (Siemens)","Christophe Fouquet (ASML)","Aiman Ezzat (Capgemini)"] },
  { day:"2026-06-17", start:"13:30", end:"14:00", stage:"Stage One", theme:"sovereignty", title:"Financing Digital Sovereignty: From Strategy to Execution", speakers:["Lutz Diederichs (BNP Paribas Germany)","Nadja Baulecke (Schwartz Digits)","Jennifer Schenker (The Innovator)"] },
  { day:"2026-06-17", start:"14:00", end:"14:35", stage:"Stage One", theme:"sovereignty", title:"The New Rules of Scale and Resilience", speakers:["Gary Wingrove (KPMG)","Hans Vestberg (Verizon)","Kamal Ahmed (Fortune)"] },
  { day:"2026-06-17", start:"14:00", end:"14:40", stage:"Black Stage", theme:"scale", title:"Capital Without Borders: The Regional Evolution of Venture Investment", speakers:["Nahoko Hoshino (Softbank Vision Fund)","Stéphanie Hospital (OneRagtime)","Alexandra York (Forbes)"] },
  { day:"2026-06-17", start:"14:00", end:"14:45", stage:"Purple Stage", theme:"energy", title:"The Hungry AI: Fixing the Energy Conundrum", speakers:["Philippe Rambach (Schneider Electric)","Nicolas Lefevre-Marton (ENGIE)","Siddarth Singh (IEA)"] },
  { day:"2026-06-17", start:"14:00", end:"14:30", stage:"Red Stage", theme:"sovereignty", title:"Love, Loneliness, and Algorithms: Inside Our Relationships with AI", speakers:["Daniel Barcay (Center for Humane Technology)","Chloé Clavel (Institut Polytechnique de Paris)","Dor Skuler (ElliQ)"] },
  { day:"2026-06-17", start:"14:00", end:"14:30", stage:"Business Redefined Arena", theme:"cyber", title:"Sovereign AI: Awakening the “sleeping giant” for business & national security", speakers:["EY"] },
  { day:"2026-06-17", start:"14:00", end:"14:25", stage:"Future of Industries Arena", theme:"health", title:"No child should face cancer alone: Healthcare journeys with companion robots", speakers:["Julien Welmant (Institut du Cancer de Montpellier)"] },
  { day:"2026-06-17", start:"14:00", end:"14:55", stage:"Sovereignty Arena", theme:"sovereignty", title:"Free, Open and Commons: New Paths to Sovereignty", speakers:["Meredith Whittaker (Signal)","Henri Verdier (Fondation Inria)","Roberto Di Cosmo (Software Heritage)"] },
  { day:"2026-06-17", start:"14:00", end:"14:30", stage:"Executive Arena", theme:"ai", title:"AI & the Future of the Knowledge Economy: Law, Finance & Consulting", speakers:["Gabrielle Halpern (Philosophe)","Julien Tanguy (Lefebvre Group)"] },
  { day:"2026-06-17", start:"14:00", end:"14:45", stage:"Investor Lounge", theme:"scale", title:"LP Fundraising in 2026: Where is capital going?", speakers:["Teodora Ene (BPI Fund of Funds)","Ketevan Liparteliani (IFC)","Thomas Schneider (Isomer Capital)"] },
  { day:"2026-06-17", start:"14:00", end:"14:10", stage:"Discovery Stage", theme:"energy", title:"Mobility & Smart Cities — Live Demo with CycloTech", speakers:["Marcus Bauer (CycloTech)"] },
  { day:"2026-06-17", start:"14:05", end:"14:55", stage:"Pitch Studio", theme:"scale", title:"Final of the AfricaTech Award: Shape the Future of African Innovation", speakers:["Zachariah George (Launch Africa Ventures)","Peter Hopwood"] },
  { day:"2026-06-17", start:"14:10", end:"14:35", stage:"VivaTech Theater", theme:"ai", title:"Beyond Language Models: Building AI that Understands the World", speakers:["Yann LeCun (AMI Labs)","Steven Levy (Wired)"] },
  { day:"2026-06-17", start:"14:15", end:"14:25", stage:"Discovery Stage", theme:"energy", title:"Mobility & Smart Cities — Live Demo with Pickwheel", speakers:["Aïssam Moujoud (Pickwheel)","Hassan Moujoud (Pickwheel)"] },
  { day:"2026-06-17", start:"14:30", end:"15:15", stage:"Founders Arena", theme:"scale", title:"The Art of the Product Pivot", speakers:["Patrick Chatain (Contentsquare)","Somayeh Taheri (UrbanChain)","Romain Dilliet (Hypertext.fyi)"] },
  { day:"2026-06-17", start:"14:30", end:"14:55", stage:"Business Redefined Arena", theme:"ai", title:"Can AI Drive Food Sovereignty, Innovation, and Decarbonization?", speakers:["Simon Bussy (Califrais)","Mehdi Gmar (CNRS)","Marion Moreau (HN Media)"] },
  { day:"2026-06-17", start:"14:30", end:"14:55", stage:"Future of Industries Arena", theme:"health", title:"From Willpower to Design: How Digital Health Is Rewriting Chronic Care", speakers:["Roxanne Holakuyee (Abbott)","Emmanuelle Lecornet Sokol (Institut Parisien d'Endocrinologie)"] },
  { day:"2026-06-17", start:"14:30", end:"15:00", stage:"Executive Arena", theme:"ai", title:"AI adoption by employees: turning usage into value for organisations", speakers:["Isabelle Hilali (datacraft)","Aldrick Zappellini (Crédit Agricole)","Nicolas Crozatier (LaborIA, Inria)"] },
  { day:"2026-06-17", start:"14:30", end:"14:40", stage:"Discovery Stage", theme:"energy", title:"Mobility & Smart Cities — Live Demo with Skwheel", speakers:["Thibaut Parmentier (Skwheel)"] },
  { day:"2026-06-17", start:"14:35", end:"15:05", stage:"Red Stage", theme:"sovereignty", title:"Investing Beyond Borders: Building New Innovation Corridors Across MENA", speakers:["Tajeddine Seif (K&K Group)","Dror Bin (Israel Innovation Authority)"] },
  { day:"2026-06-17", start:"14:45", end:"15:25", stage:"Black Stage", theme:"scale", title:"Deal or Data? How AI Is Rewriting the Rules of Venture Capital", speakers:["Clément Aglietta (Edda)","Christian Nagel (Earlybird)","Pauline Roux (ELAIA)"] },
  { day:"2026-06-17", start:"14:45", end:"14:55", stage:"Discovery Stage", theme:"energy", title:"Mobility & Smart Cities — Live Demo with Strutt", speakers:["Stéphane Bohbot (Innov8 Group)","Serge Simon (Innov8)"] },
  { day:"2026-06-17", start:"14:50", end:"15:35", stage:"Purple Stage", theme:"energy", title:"Survival of the Greenest: The Future of Sustainable Energy", speakers:["Clemence Fischer (ENGIE)","Tim Heal (Octopus Energy)","Li Wenxuan (PCG Power)"] },
  { day:"2026-06-17", start:"14:50", end:"15:35", stage:"Investor Lounge", theme:"sovereignty", title:"Reindustrializing through venture capital: Europe's bet on its own champions", speakers:["Jacques Darcy (EIF)","Arthur Negre (France Digitale)","Aurélie Nicolas (Wind Capital)"] },
  { day:"2026-06-17", start:"15:00", end:"15:30", stage:"Business Redefined Arena", theme:"ai", title:"Longevity Tips for Personal Vitality & Business Resilience — L'Oréal and PwC", speakers:["Delphine Viguier (L'Oréal)","Pauline Adam Kalfon (PwC)","Jeremy Wilks (Euronews)"] },
  { day:"2026-06-17", start:"15:00", end:"15:25", stage:"Sovereignty Arena", theme:"sovereignty", title:"Building Sovereign Scale in Europe", speakers:["Vincent Luciani (Artefact)"] },
  { day:"2026-06-17", start:"15:00", end:"15:30", stage:"Executive Arena", theme:"ai", title:"Hu-Ma Shift Consortium: Decoding humanity to demystify AI", speakers:["Mohamed Senhadji (Engie)"] },
  { day:"2026-06-17", start:"15:00", end:"15:10", stage:"Discovery Stage", theme:"energy", title:"Mobility & Smart Cities — Live Demo with Ethylowheel", speakers:["Julie Bruguière (Ethylowheel)"] },
  { day:"2026-06-17", start:"15:05", end:"15:55", stage:"Pitch Studio", theme:"scale", title:"Final of the Innovation of the Year: Crowning the Best in Innovation", speakers:["Peter Hopwood"] },
  { day:"2026-06-17", start:"15:10", end:"15:55", stage:"Red Stage", theme:"sovereignty", title:"When AI Systems Decide, Where Does Responsibility Reside?", speakers:["Antoine Bosselut (EPFL)","Arianna Legovini (World Bank Group)","Bruno Zerbib (Orange)"] },
  { day:"2026-06-17", start:"15:15", end:"15:45", stage:"Stage One", theme:"other", title:"An Inside Job: Reskilling for a New Economy", speakers:["Becky Frankiewicz (ManpowerGroup)"] },
  { day:"2026-06-17", start:"15:15", end:"16:00", stage:"Founders Arena", theme:"scale", title:"Identifying User Needs: Lessons from Fyxer AI & Nuitée", speakers:["Med Benmansour (Nuitée)","Archie Hollingsworth (Fyxer)","Yakun Wang (Ventech)"] },
  { day:"2026-06-17", start:"15:15", end:"15:25", stage:"Discovery Stage", theme:"energy", title:"Mobility & Smart Cities — Live Demo with Voltcore", speakers:["Fabrice Bertinchamps (Voltcore)"] },
  { day:"2026-06-17", start:"15:30", end:"16:00", stage:"Black Stage", theme:"scale", title:"Beyond the Bank Branch: Bringing Back Trust to Small Business Lending", speakers:["Max Schertel (finmid)","Friederike Kunter (N26)"] },
  { day:"2026-06-17", start:"15:30", end:"16:00", stage:"Executive Arena", theme:"other", title:"Your AI strategy is firing the wrong people", speakers:["Jordan Chenevier-Truchet (Bulldozer)"] },
  { day:"2026-06-17", start:"15:30", end:"15:40", stage:"Discovery Stage", theme:"energy", title:"Mobility & Smart Cities — Demo Live with Far-a-Day", speakers:["Far-a-Day"] },
  { day:"2026-06-17", start:"15:40", end:"16:05", stage:"Purple Stage", theme:"deeptech", title:"Can Europe Lead the Fusion Race?", speakers:["Francesco Sciortino (Proxima Fusion)","Luc Rémont"] },
  { day:"2026-06-17", start:"15:40", end:"16:25", stage:"Investor Lounge", theme:"scale", title:"Venture Secondaries: price discovery, liquidity and the new reality of VC", speakers:["Alice Albizatti (Revaia)","Adrien Chaltiel (The Board Project)","Sam Lawson (Flywheel Capital)"] },
  { day:"2026-06-17", start:"15:45", end:"16:10", stage:"Stage One", theme:"sovereignty", title:"Paris Region. The Next Decade Starts Here.", speakers:["Valérie Pécresse (Région Île-de-France)","Agathe Bousquet (Publicis Groupe France)"] },
  { day:"2026-06-17", start:"15:45", end:"16:20", stage:"VivaTech Theater", theme:"sovereignty", title:"Can Europe Stand on Its Own Two Feet in Tech?", speakers:["Nick Clegg (Hiro Capital)","Enrico Letta (IE University)","Maurice Lévy (Publicis Groupe)"] },
  { day:"2026-06-17", start:"15:45", end:"15:55", stage:"Discovery Stage", theme:"energy", title:"Mobility & Smart Cities — Live Demo with Momentum Technologies", speakers:["Cédric Choffat (Momentum Technologies)"] },
  { day:"2026-06-17", start:"16:00", end:"16:40", stage:"Red Stage", theme:"sovereignty", title:"Turning European Sovereignty into a Business Edge", speakers:["Mikael Bäck (Ericsson)","Catherine Jestin (Airbus)","Tanuja Randery (AWS)"] },
  { day:"2026-06-17", start:"16:00", end:"16:45", stage:"Founders Arena", theme:"scale", title:"AI Strategy: Build or Buy?", speakers:["Freddy Milesi (Sekoia)","Constantin Schröder (Arbio)","Claire Trachet (Trachet)"] },
  { day:"2026-06-17", start:"16:00", end:"16:30", stage:"Business Redefined Arena", theme:"ai", title:"AI Made in Berlin: What the German Market Is Building Right Now", speakers:["Daniel Breitinger (Bitkom)","Nadine Jüdes (Berlin Partner)","Larissa Schneider (Unframe)"] },
  { day:"2026-06-17", start:"16:00", end:"16:25", stage:"Future of Industries Arena", theme:"productivity", title:"Digitalizing and Augmenting the Supply Chain to Secure Business Continuity", speakers:["Thomas Denis (Renault Group)"] },
  { day:"2026-06-17", start:"16:00", end:"16:25", stage:"Sovereignty Arena", theme:"sovereignty", title:"Tech Sovereignty in Action: Finding Europe's Next Tech Champions", speakers:["António Campinos (European Patent Office)"] },
  { day:"2026-06-17", start:"16:05", end:"16:45", stage:"Black Stage", theme:"scale", title:"Africa Uncapped: Building Unicorns on the Continent's Own Terms", speakers:["Marie Benrubi (Partech Africa)","Zachariah George (Launch Africa)","Yehia Houry (Flat6Labs)"] },
  { day:"2026-06-17", start:"16:05", end:"16:55", stage:"Pitch Studio", theme:"health", title:"Final of the Tech for Change Award: Innovation that Moves the World Forward", speakers:["Peter Hopwood"] },
  { day:"2026-06-17", start:"16:10", end:"16:25", stage:"Stage One", theme:"health", title:"The Eye: A Window to the Outside and the Inside World", speakers:["Paul du Saillant (EssilorLuxottica)","Frederico Buffa (EssilorLuxottica)"] },
  { day:"2026-06-17", start:"16:10", end:"16:35", stage:"Purple Stage", theme:"energy", title:"The Grid Overhaul: Powering a Data-Driven World", speakers:["Philippe Piron (GE Vernova)","Shane Szarkowski (Diplomatic Courier)"] },
  { day:"2026-06-17", start:"16:25", end:"17:05", stage:"Stage One", theme:"ai", title:"The Future of Sovereign AI Is Open", speakers:["Neil Zeghidour (Gradium / Kyutai)","John Ashley (NVIDIA)","Michel-Marie Maudet (Linagora)"] },
  { day:"2026-06-17", start:"16:30", end:"17:00", stage:"Business Redefined Arena", theme:"ai", title:"AI's Foundations Are Not in the Cloud: Why Culture and Organisation Come First", speakers:["Pauline Bouvier (Manutan)","Yann Goujon (Manutan)"] },
  { day:"2026-06-17", start:"16:30", end:"16:55", stage:"Future of Industries Arena", theme:"productivity", title:"Physical AI in Action: Shaping the Next Era of Manufacturing", speakers:["Marc Fleischmann (KUKA Group)"] },
  { day:"2026-06-17", start:"16:30", end:"17:00", stage:"Sovereignty Arena", theme:"sovereignty", title:"Resilience by Design: Crypto Lessons for Digital Sovereignty", speakers:["Nicolas Bacca (ZKNOX)"] },
  { day:"2026-06-17", start:"16:30", end:"17:00", stage:"Executive Arena", theme:"energy", title:"Sustainable Energy Abundance for AI", speakers:["Sundeep Bajikar (Applied Materials)"] },
  { day:"2026-06-17", start:"16:30", end:"17:00", stage:"Discovery Stage", theme:"creative", title:"The AI Creative Studio: High-Precision Tools for Next-Level Storytelling", speakers:["Webedia / Human After All"] },
  { day:"2026-06-17", start:"16:40", end:"17:05", stage:"Purple Stage", theme:"ai", title:"First-Mile Intelligence: Where Commodity Markets Are Really Won and Lost", speakers:["Caroline Grey (Treefera)","Paul Lehair (AlbionVC)"] },
  { day:"2026-06-17", start:"16:45", end:"17:15", stage:"Red Stage", theme:"sovereignty", title:"Humans, Agents, and the Future of Hospitality", speakers:["Siddhartha Chatterjee (Club Med)","Uptin Saiidi (Tech & Money)"] },
  { day:"2026-06-17", start:"16:45", end:"17:30", stage:"Founders Arena", theme:"scale", title:"Rapid Product-Market Fit: Test, Learn, Scale", speakers:["Fabrizio Del Maffeo (Axelera AI)","Louisa Mesnard (ELAIA)","Sebastiao Zaragoza (GetVocal)"] },
  { day:"2026-06-17", start:"17:00", end:"17:45", stage:"Black Stage", theme:"scale", title:"Digital Sovereignty in the AI Era: Balancing Innovation and Control (Smart Talks with IBM)", speakers:["Malcolm Gladwell","Ana Paula De Jesus Assis (IBM)","Giovanni D'Aniello (AXA)"] },
  { day:"2026-06-17", start:"17:00", end:"17:25", stage:"Future of Industries Arena", theme:"other", title:"From China's Leading Digital Economy City to the Nation's Largest Digital Trade Expo", speakers:["Allen Bai (Hangzhou Expo Group)"] },
  { day:"2026-06-17", start:"17:00", end:"17:25", stage:"Sovereignty Arena", theme:"scale", title:"Building a National Startup Ecosystem: Oman's Journey from Vision to Impact", speakers:["Sulaiman Al Rawahi (Oman Investment Authority)"] },
  { day:"2026-06-17", start:"17:00", end:"17:30", stage:"Executive Arena", theme:"creative", title:"20 years of storytelling: How brands stay relevant in an evolving media landscape", speakers:["Helen Collerton (CNN Create)"] },
  { day:"2026-06-17", start:"17:05", end:"17:45", stage:"Stage One", theme:"deeptech", title:"Europe at the Frontier? DeepTech, Defense and the Race for Critical Technologies", speakers:["Philippe Keryer (Thales)","André Loesekrug-Pietri (JEDI)","Francesco Sciortino (Proxima Fusion)"] },
  { day:"2026-06-17", start:"17:05", end:"17:55", stage:"Pitch Studio", theme:"other", title:"Final of the Next Startupper Award: Championing the Next Generation of Entrepreneurs", speakers:["Peter Hopwood"] },
  { day:"2026-06-17", start:"17:05", end:"17:15", stage:"Discovery Stage", theme:"energy", title:"Mobility & Smart Cities — Live Demo with Avatar Mobilité", speakers:["Avatar Mobilité"] },
  { day:"2026-06-17", start:"17:30", end:"18:00", stage:"Executive Arena", theme:"other", title:"Explaining AI to 5th graders: I got schooled (and it felt amazing)", speakers:["Norbert Jeff Nadir (Zenika)"] },
];
